alter table public.slots
  add column if not exists rtp numeric,
  add column if not exists volatility text,
  add column if not exists reels integer,
  add column if not exists max_win_multiplier numeric,
  add column if not exists min_bet numeric,
  add column if not exists max_bet numeric,
  add column if not exists features jsonb not null default '[]'::jsonb,
  add column if not exists tags text[] not null default '{}'::text[],
  add column if not exists status text not null default 'live',
  add column if not exists is_featured boolean not null default false,
  add column if not exists sort_order integer not null default 0,
  add column if not exists updated_at timestamptz not null default timezone('utc', now()),
  add column if not exists created_by text,
  add column if not exists updated_by text,
  add column if not exists description text,
  add column if not exists release_date text,
  add column if not exists paylines integer,
  add column if not exists theme text,
  add column if not exists confidence_score numeric,
  add column if not exists image_safety_status text,
  add column if not exists moderation_status text,
  add column if not exists release_year integer,
  add column if not exists source_citations text[] not null default '{}'::text[],
  add column if not exists ai_extracted_at timestamptz,
  add column if not exists verified_at timestamptz,
  add column if not exists compliance_ok boolean,
  add column if not exists ingestion_version text,
  add column if not exists deleted_at timestamptz,
  add column if not exists twitch_safe boolean;
